### ISSUE TITLE
Error when running server: org.bouncycastle.asn1.ASN1Sequence are in unnamed module of loader 'app'

### ISSUE THREAD

**Issue by beri-sela** [madeindra/setup-guide#25]
Thanks for this guide. Please I get the following error when I run the server.  I have edited the line `service/src/main/java/org/whispersystems/textsecuregcm/gcp/CanonicalRequestSigner.java` as stated in the instructions but no change. 

Server : 3.21

Please also tell me where I can download version 2.92 if it's more stable.

---

INFO  [2021-01-21 17:13:01,997] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-01-21 17:13:02,001] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-01-21 17:13:02,790] com.turo.pushy.apns.ApnsClientBuilder: Native SSL provider is available; will use native provider.
org.bouncycastle.openssl.PEMException: class org.bouncycastle.asn1.DERApplicationSpecific cannot be cast to class org.bouncycastle.asn1.ASN1Sequence (org.bouncycastle.asn1.DERApplicationSpecific and org.bouncycastle.asn1.ASN1Sequence are in unnamed module of loader 'app')
        at org.bouncycastle.openssl.PEMReader$KeyPairParser.readKeyPair(Unknown Source)
        at org.bouncycastle.openssl.PEMReader$RSAKeyPairParser.parseObject(Unknown Source)
        at org.bouncycastle.openssl.PEMReader.readObject(Unknown Source)
        at org.whispersystems.textsecuregcm.gcp.CanonicalRequestSigner.initializeRsaSigningKey(CanonicalRequestSigner.java:65)
        at org.whispersystems.textsecuregcm.gcp.CanonicalRequestSigner.<init>(CanonicalRequestSigner.java:24)
        at org.whispersystems.textsecuregcm.controllers.AttachmentControllerV3.<init>(AttachmentControllerV3.java:46)
        at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:304)
        at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:151)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:406)
Caused by: java.lang.ClassCastException: class org.bouncycastle.asn1.DERApplicationSpecific cannot be cast to class org.bouncycastle.asn1.ASN1Sequence (org.bouncycastle.asn1.DERApplicationSpecific and org.bouncycastle.asn1.ASN1Sequence are in unnamed module of loader 'app')

**Comment by madeindra** [comment]
@beri-sela this could be related to your config, please check your RSA format. 

You can download v2.92 from the same repository, just browse older commits
[Signal-Server v2.92](https://github.com/signalapp/Signal-Server/tree/4468b5a2e4667f88944fa7da9862ac804d41f2c1)

**Comment by beri-sela** [comment]
@madeindra thanks for your reply.
I used the steps mentioned [here](https://github.com/madeindra/setup-guide/tree/master/signal-server-self-signed-certificate) to generate the certificate and key files, since those in the sample config gave me the same error. I don't want to use apn and cds for now so I'm just filling up the values. Do I need valid credentials for this or could it be related to my system configuration or maybe I need to run everything as root user? 

---
Ubuntu 20.04.1 LTS with Openssl 1.1.1f

**Comment by madeindra** [comment]
@beri-sela let me clarify this, if any of your config need RSA keypair and you want to left it unconfigured, you still need to fill it with random key in a proper RSA format.

You can generate it randomly on your machine. Abkut your ubuntu version, I've not tested the step with 20.04, only 18.04 but I think it won't be a big problem.

**Comment by beri-sela** [comment]
Generating the right RSA key solved the issue. Thanks.
