### ISSUE TITLE
Not transmitting over pipe

### ISSUE THREAD

**Issue by juvebogdan** [madeindra/setup-guide#7]
Hello,

I am following the guide and finished server and android. But when i started emulators and tried sending messages I am seeing this  error Not transmitting over pipe in the log. Server shows all ok.

Just to mention that i used minio setup and localstack for sqs. Not sure about this sqs part as well. I just ran localstack and created fifo queue. Does android client need sqs?

Can you help me with this?
Regards

**Comment by madeindra** [comment]
Can you post some logs?
SQS is not a mandatory requirement, AFAIK it is only for CDS.

**Comment by juvebogdan** [comment]
[SenderPhone.txt](https://github.com/madeindra/setup-guide/files/5022158/SenderPhone.txt)
[ReceiverPhone.txt](https://github.com/madeindra/setup-guide/files/5022159/ReceiverPhone.txt)

I attached two log files. I am unable to send messages at all between these two emulators. Thanks for replying quickly

**Comment by madeindra** [comment]
@juvebogdan I can see the message was sent, but if you can't receive it, try closing both app, then open it again.

Meanwhile, have you setup UnidentifiedDelivery & UNIDENTIFIED_SENDER_TRUST_ROOT correctly?

**Comment by juvebogdan** [comment]
Closing and opening again does not make any difference. What I did with Unidentified Delivery is the following:

Generate value for UnidentifiedDelivery
You will get key pair using this command (keep the keypair, you will need it for Android and for the next step)

java -jar service/target/TextSecureServer-2.92.jar certificate -ca
Use the Private key to generate certificate (key id can be random, i use 1234)

java -jar service/target/TextSecureServer-2.92.jar certificate --key <priv_key_from_step_above> --id <the_key_ID>

I copied the certificate into config.yml on the server in this position:

unidentifiedDelivery:
  certificate: XXXXXXXXXXXXXXXX # Change this to your generated certificate
  privateKey: XXXXXXXXXXXXXXXX= # Change this to you generated private key
  expiresDays: 365

and copied public key into android gradle in this position:
buildConfigField "String", "UNIDENTIFIED_SENDER_TRUST_ROOT", "\"public-key-generated-in-signal-server-step-3\""

Thats it.

**Comment by juvebogdan** [comment]
I do see now in the logs the following error:

2020-08-04 16:02:13.074 8172-8225/org.thoughtcrime.securesms D/WakeLockUtil: Released wakelock with tag: signal:e76b9700-0ea0-478d-884c-7f4735c27e41
2020-08-04 16:02:13.075 8172-8225/org.thoughtcrime.securesms E/AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
    Process: org.thoughtcrime.securesms, PID: 8172
    java.lang.AssertionError: org.whispersystems.libsignal.InvalidKeyException: Bad key type: 10
        at org.thoughtcrime.securesms.crypto.UnidentifiedAccessUtil.getCertificateValidator(UnidentifiedAccessUtil.java:35)
        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.handleMessage(PushDecryptMessageJob.java:155)
        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.onRun(PushDecryptMessageJob.java:111)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
     Caused by: org.whispersystems.libsignal.InvalidKeyException: Bad key type: 10
        at org.whispersystems.libsignal.ecc.Curve.decodePoint(Curve.java:49)
        at org.thoughtcrime.securesms.crypto.UnidentifiedAccessUtil.getCertificateValidator(UnidentifiedAccessUtil.java:32)
        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.handleMessage(PushDecryptMessageJob.java:155) 
        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.onRun(PushDecryptMessageJob.java:111) 
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21) 
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82) 
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46) 
2020-08-04 16:02:13.076 8172-8225/org.thoughtcrime.securesms E/UncaughtExceptionLogger: java.lang.AssertionError: org.whispersystems.libsignal.InvalidKeyException: Bad key type: 10
        at org.thoughtcrime.securesms.crypto.UnidentifiedAccessUtil.getCertificateValidator(UnidentifiedAccessUtil.java:35)
        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.handleMessage(PushDecryptMessageJob.java:155)
        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.onRun(PushDecryptMessageJob.java:111)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
     Caused by: org.whispersystems.libsignal.InvalidKeyException: Bad key type: 10
        at org.whispersystems.libsignal.ecc.Curve.decodePoint(Curve.java:49)
        at org.thoughtcrime.securesms.crypto.UnidentifiedAccessUtil.getCertificateValidator(UnidentifiedAccessUtil.java:32)
        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.handleMessage(PushDecryptMessageJob.java:155) 
        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.onRun(PushDecryptMessageJob.java:111) 
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21) 
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82) 
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)

**Comment by madeindra** [comment]
Can you share me some value you got from the generation process?
Just generate a new value that you will not use, so it will not compromise your server.

send 2 value from this command
```
java -jar service/target/TextSecureServer-2.92.jar certificate -ca
```

and 2 value from this command
```
java -jar service/target/TextSecureServer-2.92.jar certificate --key <priv_key_from_step_above> --id <the_key_ID>
```

**Comment by juvebogdan** [comment]
First command:
Public key : BWkPVhh0nXKsBOzkFftrOngNzRWAZjNFl1lz0eDgUxkI
Private key: UNygHb/P4g6YeaLO3Gn5S4UcU5jqyELyCJvGKpX7b2c=

Second one:
Certificate: CiYI0gkSIQXKTrOSYyn5cpl0av5U/KpV5SxydfMQUZM8HxItjbl/IxJAv1MT9iTkq054ZYHYTij4bddn+zoSFLYEJDEZhevYTLNBbFjfqKWaPsh9fcEAvFGfTxb+9ejUGWtAgT7ZJIz+iA==
Private key: IPjhSgaf0dZOviaN0nCalJoinPSE4a8PXrw9YA6Pe0U=

As id I didnt use 1234.

**Comment by madeindra** [comment]
@juvebogdan this should be the correct value, as long as you didn't mistake the first and second private key.

I'm confused about this error too. Is GCM already setup correctly?

**Comment by juvebogdan** [comment]
Do I put the first or second private key to the server settings?

**Comment by madeindra** [comment]
> First command:
> Public key : BWkPVhh0nXKsBOzkFftrOngNzRWAZjNFl1lz0eDgUxkI
> Private key: UNygHb/P4g6YeaLO3Gn5S4UcU5jqyELyCJvGKpX7b2c=
> 
> Second one:
> Certificate: CiYI0gkSIQXKTrOSYyn5cpl0av5U/KpV5SxydfMQUZM8HxItjbl/IxJAv1MT9iTkq054ZYHYTij4bddn+zoSFLYEJDEZhevYTLNBbFjfqKWaPsh9fcEAvFGfTxb+9ejUGWtAgT7ZJIz+iA==
> Private key: IPjhSgaf0dZOviaN0nCalJoinPSE4a8PXrw9YA6Pe0U=

@juvebogdan In this case, you should use the certificate & second private key for the server
 
```
unidentifiedDelivery:
  certificate: CiYI0gkSIQXKTrOSYyn5cpl0av5U/KpV5SxydfMQUZM8HxItjbl/IxJAv1MT9iTkq054ZYHYTij4bddn+zoSFLYEJDEZhevYTLNBbFjfqKWaPsh9fcEAvFGfTxb+9ejUGWtAgT7ZJIz+iA==
  privateKey: IPjhSgaf0dZOviaN0nCalJoinPSE4a8PXrw9YA6Pe0U== 
  expiresDays: 365
```

While on the client app, you use the public key

```
buildConfigField "String", "UNIDENTIFIED_SENDER_TRUST_ROOT", "\"BWkPVhh0nXKsBOzkFftrOngNzRWAZjNFl1lz0eDgUxkI\""
```

**Comment by juvebogdan** [comment]
Thank you for your help. Not sure where was my mistake but i just redone everything and messages work now
